//! Renders the portfolio landing page: Dioxus RSX in, one static HTML file out.
//!
//! Deliberately *not* `dx bundle --ssg`. That path ships a WASM bundle and hydrates,
//! and it is broken for exactly this deployment shape -- GitHub Pages serves this repo
//! under `/pursuit-l2-portfolio/`, and `base_path` with `dx bundle` is DioxusLabs/dioxus
//! #3942, open with no fix. Rendering a VirtualDom to a String sidesteps all of it:
//! no router, no hydration, no bundle, no base path to get wrong. The output is the
//! same single self-contained file the page has always been, and the browser does not
//! know or care that Rust produced it.

mod content;
mod theme;

use content::*;
use dioxus::prelude::*;
use theme::*;

const STYLE: &str = include_str!("../assets/style.css");
const FIELD_JS: &str = include_str!("../assets/field.js");
const FONTS: &str = "https://fonts.googleapis.com/css2?family=Archivo:wght@700\
&family=Fraunces:opsz,wght@9..144,400;9..144,600;9..144,700\
&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500\
&family=Manrope:wght@800&family=Source+Serif+4:opsz,wght@8..60,600&display=swap";

fn main() -> std::io::Result<()> {
    let body = dioxus_ssr::render_element(rsx! { Page {} });
    let css = STYLE.replace("/*@THEMES@*/", &themes_css());

    let html = format!(
        "<!doctype html>\n\
         <html lang=\"en\">\n\
         <head>\n\
         <meta charset=\"utf-8\">\n\
         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
         <title>Stan (Aisling) Leiva-Davila — Pursuit L2</title>\n\
         <meta name=\"description\" content=\"Four cycles, four shipped products. Pursuit AI-Native Builder, inaugural cohort.\">\n\
         <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n\
         <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n\
         <link href=\"{FONTS}\" rel=\"stylesheet\">\n\
         <style>\n{css}\n</style>\n\
         </head>\n\
         <body>\n\
         <canvas id=\"field\" aria-hidden=\"true\"></canvas>\n\
         {body}\n\
         <script>\n{FIELD_JS}\n</script>\n\
         </body>\n\
         </html>\n"
    );

    let out = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../index.html");
    std::fs::write(&out, &html)?;
    eprintln!(
        "wrote {} ({} bytes, {} themes, {} builds)",
        out.display(),
        html.len(),
        THEMES.len(),
        BUILDS.len()
    );
    Ok(())
}

/// Emits the per-theme custom-property blocks.
///
/// The contrast figure in each comment is *computed*, not typed, so those comments
/// cannot drift away from the colours they describe. A hand-written comment claiming
/// a ratio nobody rechecks is the same failure as HouseCheck's export comment that
/// said "compare with the published one" while nothing published it.
fn themes_css() -> String {
    let mut s = String::from(
        "/* ── the four themes ──────────────────────────────────────────────────────\n\
         \x20  GENERATED by site/src/theme.rs -- edit the Rust, not this block.\n\
         \x20  Hex values were sampled from this repo's own screenshots. Contrast ratios\n\
         \x20  in the comments are computed from those values at build time, and every\n\
         \x20  pairing is additionally held to WCAG 4.5:1 by a const assertion, so an\n\
         \x20  unreadable theme fails the build rather than shipping.\n\
         \x20  ───────────────────────────────────────────────────────────────────────── */\n",
    );

    for t in THEMES {
        let ink_ratio = contrast_x100(t.ink, t.surface) as f64 / 100.0;
        let accent_ratio = contrast_x100(t.accent, t.surface) as f64 / 100.0;
        s.push_str(&format!(
            "\n.t-{slug}{{\n\
             \x20 --surface:{surface};\n\
             \x20 --card-ink:{ink};                    /* {ink_ratio:.2}:1 */\n\
             \x20 --card-ink-2:{ink2};\n\
             \x20 --accent:{accent};                      /* {accent_ratio:.2}:1 */\n\
             \x20 --chip:{chip};\n\
             \x20 --chip-ink:{chip_ink};\n\
             \x20 --edge:{edge};\n\
             \x20 --face:{face};\n\
             \x20 --face-size:{fsize};--face-track:{ftrack};\n\
             }}\n\
             .t-{slug} .shotwrap{{--chrome:{chrome};--shot-bg:{shot_bg}}}\n",
            slug = t.slug,
            surface = t.surface.hex(),
            ink = t.ink.hex(),
            ink2 = t.ink.alpha(t.ink_alpha),
            accent = t.accent.hex(),
            chip = t.chip,
            chip_ink = t.chip_ink.hex(),
            edge = t.ink.alpha(t.edge_alpha),
            face = t.face,
            fsize = t.face_size,
            ftrack = t.face_track,
            chrome = t.chrome_pct,
            shot_bg = t.shot_bg.hex(),
        ));
        if let Some(live) = t.live_ink {
            s.push_str(&format!(
                ".t-{} .tag.live{{color:{}}}   /* {:.2}:1 inside the dark chip */\n",
                t.slug,
                live.hex(),
                contrast_x100(live, Rgb(0x3B, 0x3B, 0x3D)) as f64 / 100.0,
            ));
        }
        if let Some(h) = t.hover {
            s.push_str(&format!(".t-{}:hover{{border-color:{}}}\n", t.slug, h.hex()));
        }
    }
    s
}

#[component]
fn Page() -> Element {
    rsx! {
        div { class: "wrap",
            Masthead {}

            h2 { class: "sec", "The builds" }
            div { class: "builds",
                for b in BUILDS {
                    BuildCard { b: b }
                }
            }

            h2 { class: "sec far", "If you only read one thing" }
            ExportStory {}

            h2 { class: "sec far", "Why Rust, specifically" }
            RustArgument {}
            Stack { rows: RUST_ROWS, top: true }

            h2 { class: "sec far", "How I work" }
            div { class: "rules",
                for r in RULES {
                    div { class: "rule",
                        h4 { "{r.head}" }
                        p { "{r.body}" }
                    }
                }
            }

            h2 { class: "sec far", "Stack" }
            Stack { rows: STACK_ROWS, top: false }

            footer {
                "Pursuit AI-Native Builder — inaugural cohort · 600+ hours over seven months"
                br {}
                "Each card carries its own project's palette and display face, sampled from that
                 project's screenshots in this repo. The frame around them never changes. This page
                 is rendered from Rust by "
                code { "site/" }
                " — Dioxus RSX in, static HTML out, no WASM and no hydration."
            }
        }
    }
}

#[component]
fn Masthead() -> Element {
    rsx! {
        header {
            p { class: "eyebrow", "Pursuit AI-Native Builder · Inaugural cohort" }
            h1 {
                "Four cycles."
                br {}
                "Four "
                em { "shipped" }
                " products."
            }
            p { class: "deck",
                b { "Every one runs." }
                " Two are live on the internet right now; two are desktop applications you compile
                 and launch."
            }
            div { class: "meta",
                span { "Stan (Aisling) Leiva-Davila" }
                a { href: "https://github.com/nessaisling-lab", "github.com/nessaisling-lab" }
                a { href: "https://linkedin.com/in/stan-leiva-davila", "LinkedIn" }
                a { href: "mailto:ness.aisling@gmail.com", "ness.aisling@gmail.com" }
            }
        }
    }
}

#[component]
fn BuildCard(b: &'static Build) -> Element {
    let mut class = format!("build t-{}", b.theme.slug);
    if b.lead {
        class = format!("build build--lead t-{}", b.theme.slug);
    }
    rsx! {
        a { class: "{class}", href: "{href(b)}",
            div { class: "body",
                div { class: "top",
                    h3 { "{b.name}" }
                    span { class: "num", "{b.cycle}" }
                    if let Some(f) = b.flag {
                        span { class: "flag", "{f}" }
                    }
                }
                p { "{b.blurb}" }
                div { class: "tags",
                    for t in b.tags {
                        span { class: if t.live { "tag live" } else { "tag" }, "{t.label}" }
                    }
                }
            }
            div { class: "shotwrap",
                img {
                    class: "shot",
                    src: "{b.shot}",
                    alt: "{b.alt}",
                    loading: if b.lead { "eager" } else { "lazy" },
                }
            }
        }
    }
}

#[component]
fn ExportStory() -> Element {
    rsx! {
        div { class: "pull t-housecheck",
            h3 { "The export that found its own hole" }
            p {
                "A tenant lawyer can read a building's violations on any city website. What they
                 cannot do is put that reading in front of a court, because a printout is
                 unverifiable. HouseCheck's export carries an append-only hash chain and an Ed25519
                 signature, so opposing counsel can re-check it offline — without trusting us and
                 without reaching our servers."
            }
            p {
                "The part I am prouder of than the cryptography: while verifying it in production I
                 wrote an independent verifier in another language, and found that "
                span { class: "hi", "signing alone was not enough" }
                ". A forger who rewrites a row, recomputes the whole chain and signs it with their
                 own keypair produces a document that verifies as intact — because it is internally
                 consistent. A row rewritten to "
                code { "NO VIOLATIONS OF ANY KIND AT THIS ADDRESS" }
                " passed cleanly."
            }
            p {
                "The fix was publishing the public key at a stable endpoint, so a reader has
                 something to compare against. That hole existed because the code's own comment
                 said "
                em { "“compare with the published one”" }
                " while nothing published it."
            }
        }
    }
}

#[component]
fn RustArgument() -> Element {
    rsx! {
        div { class: "pull",
            h3 { "Three of the four have a property a type system can defend." }
            p {
                "HouseCheck signs a document a court might rely on. SiteAssure keeps a safety log
                 that has to stay tamper-evident. Resona promises that audio never leaves the
                 machine. In each case the product's whole claim is a guarantee about what the
                 program will "
                em { "not" }
                " do — and a guarantee is easier to hold when the compiler is checking it than when
                 a test suite is remembering to."
            }
            p {
                "The practical payoff is boring and real: a read-only SQLite artefact baked into a
                 container with "
                span { class: "hi", "no database server and no connection pool" }
                "; a desktop app that ships one binary; "
                span { class: "hi", "149 tests and clippy-clean" }
                " on the current build, with correctness bugs re-measured across the whole dataset
                 rather than spot-checked. This page is the smallest example: its four card themes
                 are Rust values, and a "
                code { "const" }
                " assertion refuses to compile any theme whose text falls below WCAG 4.5:1 on its
                 own background."
            }
        }
    }
}

#[component]
fn Stack(rows: &'static [Row], top: bool) -> Element {
    rsx! {
        dl {
            class: "stack",
            style: if top { "margin-top:26px" } else { "" },
            for r in rows {
                div { class: "row",
                    dt { "{r.dt}" }
                    dd { "{r.dd}" }
                }
            }
        }
    }
}
